matrix:
  include:
    - language: node_js
      node_js:
        - 0.12
      before_install:
        # setting the path for phantom.js 2.0.0
        - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
        # starting a GUI to run tests, per https://docs.travis-ci.com/user/gui-and-headless-browsers/#using-xvfb-to-run-tests-that-require-a-gui
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - "npm config set spin false"
        - "npm install -g npm@^2"
      install:
          - mkdir travis-phantomjs
          - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
          - tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C $PWD/travis-phantomjs
          - export PATH=$PWD/travis-phantomjs:$PATH
          - npm install -g bower
          - npm install
          - bower install
      script:
          - ember test --server

    - language: android
      android:
        components:
          - tools
          - build-tools-24.0.1
          - android-24
          - platform-tools
          - extra-android-support # because I'm use support library
          - extra-android-m2repository # because I'm use support library
          - $ANDROID_TARGET
          - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
        licenses:
          - '.+'

      sudo: required

      jdk:
        - oraclejdk8

      install: true

      before_script:
        - chmod +x ./App_mobile/gradlew

      script:
        - cd ./App_mobile
        - ./gradlew assembleRelease --stacktrace

      after_success:
        - bash <(curl -s https://codecov.io/bash)
