notifications:
  slack: healthsafe:yjWOO4vhSSuvJ4g9ehyYXyxF

language: node_js
node_js: stable
  script:
    - cd API && npm start

services:
  - mongodb

deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: "92116a61-f8e6-42fd-9008-6ff73e839343"
