
notifications:
  slack: healthsafe:yjWOO4vhSSuvJ4g9ehyYXyxF

matrix:
  include:
    - language: node_js
      node_js:
        - 0.12
      script:
        - cd ./App_web && npm test

    - language: android
      android:
        components:
          - tools
          - build-tools-24.0.1
          - android-24
          - platform-tools
          - extra-android-support # because I'm use support library
          - extra-android-m2repository # because I'm use support library
          - $ANDROID_TARGET
          - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
        licenses:
          - '.+'

      sudo: required

      jdk:
        - oraclejdk8

      install: true

      before_script:
        - chmod +x ./App_mobile/gradlew

      script:
        - cd ./App_mobile
        - export CODACY_PROJECT_TOKEN=2d3054f2aa44489e8ffd5f52c28a042b
        - ./gradlew assembleRelease --stacktrace
        - ./gradlew testReleaseUnitTest
        - ./gradlew createReleaseCoverageReport
        - ./codacy-coverage-reporter report -l Java -r ./app/build/reports/test/testReleaseUnitTest/jacoco.xml

      after_success:
        - bash <(curl -s https://codecov.io/bash)
