
notifications:
  slack: healthsafe:yjWOO4vhSSuvJ4g9ehyYXyxF

matrix:
  include:
    - language: node_js
      node_js:
        - 0.12
      script:
    #    - cd API && npm start
    #    - cd ..
        - cd ./App_web # && npm test

    - language: android
    dist: trusty
      android:
        update_sdk: true
        components:
          - tools
          - build-tools-24.0.1
          - android-24
          - platform-tools
          - extra-android-support # because I'm use support library
          - extra-android-m2repository # because I'm use support library
          - $ANDROID_TARGET
          - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
        licenses:
          - '.+'

        before_cache:
          - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
          - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
        cache:
          directories:
            - $HOME/.gradle/caches/
            - $HOME/.gradle/wrapper/
            - $HOME/.android/build-cache

      sudo: required

      jdk:
        - oraclejdk8

      install: true

      before_script:
        - chmod +x ./App_mobile/gradlew

        # -- instrumentation tests --

        #- echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
        #- emulator -avd test -no-skin -no-audio -no-window &
        #- android-wait-for-emulator
        #- adb shell input keyevent 82 &

      script:
        - cd ./App_mobile
        - export CODACY_PROJECT_TOKEN=2d3054f2aa44489e8ffd5f52c28a042b
        - ./gradlew clean build connectedCheck -PdisablePreDex --stacktrace
        - echo "Travis branch is $TRAVIS_BRANCH"    #Print out which branch it is.
        - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"    #Print out pull request number.
        - android-wait-for-emulator             #Run wait for the emulator script.
        - adb devices                           #Display list of devices
        - adb shell input keyevent 82 &
        - ./gradlew connectedAndroidTest -PdisablePreDex --stacktrace
        
        - ./gradlew build connectedCheck
        # - ./gradlew assembleDebug --stacktrace
        # - ./gradlew generateDebugSources
        # - ./gradlew compileDebugSources
        # - ./gradlew createMockableJar
        # - ./gradlew compileDebugUnitTestSources
        # - ./gradlew preBuild
        # - ./gradlew preDebugBuild
        # - ./gradlew compileDebugAidl
        # - ./gradlew compileDebugAidl compileDebugRenderscript
        # - ./gradlew checkDebugManifest
        # - ./gradlew generateDebugBuildConfig
        # - ./gradlew prepareLintJar
        # - ./gradlew generateDebugSources
        # - ./gradlew javaPreCompileDebug
        # - ./gradlew mainApkListPersistenceDebug
        # - ./gradlew generateDebugResValues
        # - ./gradlew generateDebugResources
        # - ./gradlew mergeDebugResources
        # - ./gradlew createDebugCompatibleScreenManifests
        # - ./gradlew processDebugManifest
        # - ./gradlew processDebugResources
        # - ./gradlew compileDebugJavaWithJavac
        # - ./gradlew compileDebugSources
        # - ./gradlew createMockableJar
        # - ./gradlew generateDebugUnitTestSources
        # - ./gradlew preDebugUnitTestBuild
        # - ./gradlew javaPreCompileDebugUnitTest
        # - ./gradlew compileDebugUnitTestJavaWithJavac
        # - ./gradlew mergeDebugShaders
        # - ./gradlew compileDebugShaders
        # - ./gradlew generateDebugAssets
        # - ./gradlew mergeDebugAssets
        # - ./gradlew packageDebugUnitTestForUnitTest
        # - ./gradlew generateDebugUnitTestConfig
        # - ./gradlew processDebugJavaRes
        # - ./gradlew processDebugUnitTestJavaRes
        # - ./gradlew compileDebugUnitTestSources
        - ./gradlew testDebugUnitTest
        - ./gradlew createDebugCoverageReport --continue
        - ./codacy-coverage-reporter report -l Java -r ./app/build/reports/coverage/debug/report.xml
        - bash gradlew test jacocoTestReport

      before_install:
        - pip install --user codecov
      after_success:
        - codecov
        - bash <(curl -s https://codecov.io/bash)
      after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"

  deploy:
    skip_cleanup: true
    provider: heroku
    api_key:
      secure: "92116a61-f8e6-42fd-9008-6ff73e839343"

global:   #Optional
    - ADB_INSTALL_TIMEOUT=10    #Time out to 10 mins
#addons:
  #artifacts:
  #  paths:
  #    - .karma/
  #    - ./mocha.js
  #sauce_connect: true
  #chrome: stable
#cache:
#  directories:
#    - ~/.npm
