
notifications:
  slack: healthsafe:yjWOO4vhSSuvJ4g9ehyYXyxF

matrix:
  include:
    - language: node_js
      node_js:
        - 0.12
      script:
    #    - cd API && npm start
    #    - cd ..
        - cd ./App_web # && npm test

    - language: android
      android:
        components:
          - tools
          - build-tools-24.0.1
          - android-24
          - platform-tools
          - extra-android-support # because I'm use support library
          - extra-android-m2repository # because I'm use support library
          - $ANDROID_TARGET
          - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
        licenses:
          - '.+'

      sudo: required

      jdk:
        - oraclejdk8

      install: true

      before_script:
        - chmod +x ./App_mobile/gradlew

      script:
        - cd ./App_mobile
        - export CODACY_PROJECT_TOKEN=2d3054f2aa44489e8ffd5f52c28a042b
        - ./gradlew assembleDebug --stacktrace
        - ./gradlew generateDebugSources
        - ./gradlew compileDebugSources
        - ./gradlew createMockableJar
        - ./gradlew compileDebugUnitTestSources
        - ./gradlew preBuild
        - ./gradlew preDebugBuild
        - ./gradlew compileDebugAidl
        - ./gradlew compileDebugAidl compileDebugRenderscript
        - ./gradlew checkDebugManifest
        - ./gradlew generateDebugBuildConfig
        - ./gradlew prepareLintJar
        - ./gradlew generateDebugSources
        - ./gradlew javaPreCompileDebug
        - ./gradlew mainApkListPersistenceDebug
        - ./gradlew generateDebugResValues
        - ./gradlew generateDebugResources
        - ./gradlew mergeDebugResources
        - ./gradlew createDebugCompatibleScreenManifests
        - ./gradlew processDebugManifest
        - ./gradlew processDebugResources
        - ./gradlew compileDebugJavaWithJavac
        - ./gradlew compileDebugSources
        - ./gradlew createMockableJar
        - ./gradlew generateDebugUnitTestSources
        - ./gradlew preDebugUnitTestBuild
        - ./gradlew javaPreCompileDebugUnitTest
        - ./gradlew compileDebugUnitTestJavaWithJavac
        - ./gradlew mergeDebugShaders
        - ./gradlew compileDebugShaders
        - ./gradlew generateDebugAssets
        - ./gradlew mergeDebugAssets
        - ./gradlew packageDebugUnitTestForUnitTest
        - ./gradlew generateDebugUnitTestConfig
        - ./gradlew processDebugJavaRes
        - ./gradlew processDebugUnitTestJavaRes
        - ./gradlew compileDebugUnitTestSources
        - ./gradlew testDebugUnitTest
        - ./gradlew createDebugCoverageReport
        - ./codacy-coverage-reporter report -l Java -r ./app/build/reports/coverage/debug/report.xml

      after_success:
        - bash <(curl -s https://codecov.io/bash)
  deploy:
    skip_cleanup: true
    provider: heroku
    api_key:
      secure: "92116a61-f8e6-42fd-9008-6ff73e839343"

#addons:
  #artifacts:
  #  paths:
  #    - .karma/
  #    - ./mocha.js
  #sauce_connect: true
  #chrome: stable
#cache:
#  directories:
#    - ~/.npm
