tags:
  - name: SIGNUP
    description: TO DO
  - name: SIGNIN
    description: TO DO
  - name: DRPROFILE
    description: TO DO
  - name: PATIENTDATA
    description: TO DO
  - name: LOGOUT
    description: TO DO
  - name: DOCUMENTATION
    description: TO DO
